#!/usr/bin/env bash
set -e

# Determine the correct docker compose command
dc_base="$(docker compose version &>/dev/null && echo 'docker compose' || echo 'docker-compose')"
dc="$dc_base"

# Export host UID/GID
export PUID=$(id -u)
export PGID=$(id -g)

# Pass all arguments to the docker command
exec $dc "$@"
